### ISSUE TITLE
Support Magisk new update method

### ISSUE THREAD

**Issue by CoelacanthusHex** [Briclyaz/NLSound_module_QCom#1]
In v24.0 update, Magisk Manager remove old module repo and use a update API instead.
We should support it.
https://topjohnwu.github.io/Magisk/guides.html

**Comment by L1sa-f** [comment]
> In v24.0 update, Magisk Manager remove old module repo and use a update API instead. We should support it. https://topjohnwu.github.io/Magisk/guides.html

Done, in fact, this was done on the first day of the release of Magisk 24.0 
Wait for next version release
