### ISSUE TITLE
Device stuck in bootloop when choose float

### ISSUE THREAD

**Issue by BuT9l** [Briclyaz/NLSound_module_QCom#13]
I have 2 Xiaomi devices and when I installed NLSound v3.9 they both were stuck in bootloop, after i tested it a little bit on one of my devices I figured out that setting sound output format to float is what causing me device to enter bootloop. So, while I was writing this, I tested my second device, trying install magisk module, picking 24bit instead of float, and it successfully launched.
Devices:
Xiaomi Redmi Note 7 (lavender)
Xiaomi Mi 12 Lite (taoyao)
Both on LineageOS 20

**Comment by Briclyaz** [comment]
Hi! Your device does not support float mode, try using more loyal settings like 24-bit and 96000 Hz.
