### ISSUE TITLE
Bonjour j ai installé ce tweak mais j ai un gros problème tous les notifications sont devenu avec un son très fort

### ISSUE THREAD

**Issue by Mahdi2808** [Briclyaz/NLSound_module_QCom#17]
Bonjour j ai un problème de son côté notification et sonnerie le volume est très haut et je peux même pas le modifier même quand j ai écrit un message sur messanger à chaque message envoyé un son très fort avant le son est un peu discret aider moi comment rétablir état initial du son j ai un redmi note 9 pro

**Comment by Briclyaz** [comment]
Reinstall the module with skip 9 and 15 of the installer.

**Comment by Mahdi2808** [comment]
![Screenshot_2024-08-08-16-28-19-899_e csfhkakszkmy](https://github.com/user-attachments/assets/02f8c4aa-6b90-4260-ad2c-cc4875ab9931)

Dans étape 9 et 15 je fais install ou skip??

**Comment by Briclyaz** [comment]
Ofc skip (vol-)
